os: linux
language: java

jdk: openjdk8

services:
   - docker

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

script:
   - mvn -f VentasSpringMVC/pom.xml clean verify -Pdocker

deploy:
        provider: script
        script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy
        skip_celanup: true
        on:
                tags: true
